language: node_js
node_js:
  - 15

env:
  global:
    - CI=true

services:
  - docker    

dist: focal
addons:
  apt:
    sources:
      - sourceline: 'deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'

cache:
  directories:
    - node_modules

arch:
  - amd64

before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - sudo apt-get update
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - sudo apt-get install -y qemu-user-static binfmt-support
  - docker buildx create --use

install:
  - npm i

script:
  - docker buildx version
  - npm test
  - npm run build  
  - sh scripts/docker_buildx.sh $DOCKER_USERNAME $DOCKER_PASSWORD

deploy:
  - provider: script
    script: sh scripts/docker_buildx.sh $DOCKER_USERNAME $DOCKER_PASSWORD --push
    on:
      tags: true
  - provider: script
    script: sh scripts/docker_buildx_dev.sh $DOCKER_USERNAME $DOCKER_PASSWORD --push
    on:
      all_branches: true