language: node_js
node_js:
  - 15

env:
  CI=true

cache:
  directories:
    - node_modules

arch:
  - amd64
  - arm64

install:
  - npm i

script:
  - npm test
  - npm run build
  - sh make_docker.sh